/* eslint-disable react-refresh/only-export-components */
import DOMPurify from 'dompurify'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Printer, Copy, CloudArrowUp } from '@phosphor-icons/react'
import { toast } from 'sonner'
import type { Municipality } from '@/data/maMunicipalities'
import { type DocType, type FiscalSnapshot, fmtMoney } from './townfinderTypes'
import { escapeHtml } from '@/lib/htmlSafe'

// ── Document templates ────────────────────────────────────────────────────────

export const DOC_TEMPLATES: { type: DocType; label: string; icon: string; desc: string }[] = [
  { type: 'prr-response',        label: 'PRR Response Letter',     icon: '📬', desc: 'Formal public records request response under MGL c.66 §10.' },
  { type: 'meeting-agenda',      label: 'Board Meeting Agenda',     icon: '📋', desc: 'Open Meeting Law-compliant agenda with required headers.' },
  { type: 'budget-memo',         label: 'Budget Transfer Memo',     icon: '💰', desc: 'Finance Committee memo for budget line transfer requests.' },
  { type: 'appointment-notice',  label: 'Board Appointment Notice', icon: '📣', desc: 'Official notice of appointment or reappointment to a board.' },
  { type: 'press-release',       label: 'Press Release',            icon: '📰', desc: 'Press release template for town announcements.' },
  { type: 'annual-report-cover', label: 'Annual Report Cover',      icon: '📘', desc: 'Cover page and introduction for the annual town report.' },
]

// ── Document generation ───────────────────────────────────────────────────────

export function generateDocument(type: DocType, town: Municipality, fiscal: FiscalSnapshot): string {
  // Escape every operator-controlled value at the source so the generated HTML
  // is safe even if a downstream consumer skips DOMPurify (clipboard copy,
  // email body, vault export, etc.).
  const townName = escapeHtml(town.name)
  const townCounty = escapeHtml(town.county)
  const name = `Town of ${townName}`
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
  const fy = escapeHtml(fiscal.fiscalYear)

  const header = `
<div style="font-family: Georgia, 'Times New Roman', serif; max-width: 700px; margin: 0 auto; padding: 40px;">
  <div style="text-align:center; border-bottom: 2px solid #1e3a5f; padding-bottom: 20px; margin-bottom: 28px;">
    <h1 style="font-size:22px; font-weight:700; margin:0; color:#1e3a5f; letter-spacing:0.5px;">${escapeHtml(`Town of ${town.name}`).toUpperCase()}</h1>
    <p style="font-size:13px; margin:4px 0 0; color:#555;">${townCounty} County · Commonwealth of Massachusetts</p>
  </div>`

  const footer = `
  <div style="margin-top: 48px; border-top: 1px solid #ccc; padding-top: 16px; font-size: 11px; color: #888; text-align:center;">
    ${name} · ${townCounty} County · Commonwealth of Massachusetts · Generated by Workspace
  </div>
</div>`

  switch (type) {
    case 'prr-response':
      return `${header}
  <p style="font-size:13px; color:#555; margin:0 0 24px;">${today}</p>
  <p style="font-size:14px;"><strong>Re: Public Records Request</strong></p>
  <p style="font-size:14px; line-height:1.7;">Dear Requester,</p>
  <p style="font-size:14px; line-height:1.7;">
    In response to your public records request received by the ${name}, Office of the Town Clerk, 
    we are writing to acknowledge receipt of your request pursuant to the Massachusetts Public Records Law, 
    M.G.L. c. 66, § 10, and the regulations promulgated thereunder at 950 CMR 32.00.
  </p>
  <p style="font-size:14px; line-height:1.7;">
    [DESCRIBE RECORDS PROVIDED / EXEMPTIONS CLAIMED / ESTIMATED RESPONSE DATE]
  </p>
  <p style="font-size:14px; line-height:1.7;">
    The ${name} is required to respond to your request within ten (10) business days of receipt. 
    If additional time is needed, we will notify you of the reason and provide an estimated completion date.
  </p>
  <p style="font-size:14px; line-height:1.7; margin-top: 32px;">Sincerely,</p>
  <p style="font-size:14px; line-height:1.7; margin-top: 24px;">
    ___________________________<br/>
    Records Access Officer<br/>
    ${name}<br/>
    ${today}
  </p>
${footer}`

    case 'meeting-agenda':
      return `${header}
  <h2 style="font-size:17px; font-weight:700; text-align:center; margin:0 0 4px;">BOARD OF SELECTMEN / SELECT BOARD</h2>
  <h3 style="font-size:14px; font-weight:400; text-align:center; margin:0 0 24px; color:#555;">MEETING AGENDA · [DATE] · [TIME] · [LOCATION]</h3>
  <p style="font-size:12px; color:#666; margin-bottom:20px; font-style:italic;">
    Posted in accordance with the Massachusetts Open Meeting Law, M.G.L. c. 30A, §§ 18–25. 
    Notice posted at least 48 hours prior to the meeting, not including Saturdays, Sundays, and legal holidays.
  </p>
  <ol style="font-size:14px; line-height:2.2; padding-left:24px;">
    <li>Call to Order</li>
    <li>Pledge of Allegiance</li>
    <li>Approval of Minutes — [Previous Meeting Date]</li>
    <li>Public Comment (3 minutes per speaker)</li>
    <li>Selectmen's Reports</li>
    <li>Town Administrator's Report</li>
    <li>[AGENDA ITEM]</li>
    <li>[AGENDA ITEM]</li>
    <li>Licenses, Permits, and Warrants</li>
    <li>Executive Session — [REASON, if applicable] (M.G.L. c. 30A, § 21)</li>
    <li>Adjournment</li>
  </ol>
  <p style="font-size:12px; color:#888; margin-top:24px;">
    <em>Individuals requiring accommodations for a disability should contact the Town Clerk at least 48 hours in advance.</em>
  </p>
${footer}`

    case 'budget-memo':
      return `${header}
  <h2 style="font-size:16px; font-weight:700; margin:0 0 20px;">BUDGET TRANSFER / AMENDMENT REQUEST</h2>
  <table style="width:100%; border-collapse:collapse; font-size:13px; margin-bottom:24px;">
    <tr><td style="padding:6px 0; width:140px; font-weight:600;">To:</td><td>Finance Committee / Board of Selectmen</td></tr>
    <tr><td style="padding:6px 0; font-weight:600;">From:</td><td>[DEPARTMENT HEAD / TOWN ADMINISTRATOR]</td></tr>
    <tr><td style="padding:6px 0; font-weight:600;">Date:</td><td>${today}</td></tr>
    <tr><td style="padding:6px 0; font-weight:600;">Subject:</td><td>Budget Transfer Request — FY${fy}</td></tr>
    <tr><td style="padding:6px 0; font-weight:600;">Account:</td><td>[FROM ACCOUNT] → [TO ACCOUNT]</td></tr>
    <tr><td style="padding:6px 0; font-weight:600;">Amount:</td><td>$[AMOUNT]</td></tr>
  </table>
  <p style="font-size:14px; line-height:1.7;"><strong>Purpose:</strong></p>
  <p style="font-size:14px; line-height:1.7;">[EXPLAIN REASON FOR TRANSFER — e.g., unexpected expenditure, account over-appropriated, etc.]</p>
  <p style="font-size:14px; line-height:1.7;"><strong>Fiscal Impact:</strong></p>
  <p style="font-size:14px; line-height:1.7;">
    This transfer does not increase the total FY${fy} appropriation. Total budget remains ${fmtMoney(fiscal.operatingBudget)}.
  </p>
  <p style="font-size:14px; margin-top:32px;">Submitted by: ___________________________&nbsp;&nbsp;&nbsp; Date: _____________</p>
  <p style="font-size:14px; margin-top:16px;">Finance Director approval: ___________________________&nbsp;&nbsp;&nbsp; Date: _____________</p>
${footer}`

    case 'appointment-notice':
      return `${header}
  <h2 style="font-size:16px; font-weight:700; margin:0 0 20px;">NOTICE OF APPOINTMENT</h2>
  <p style="font-size:14px; line-height:1.7;">
    Notice is hereby given that the Board of Selectmen of the ${name} has appointed the following individual to serve on the [BOARD/COMMITTEE NAME]:
  </p>
  <table style="width:100%; border-collapse:collapse; font-size:14px; margin:20px 0; border:1px solid #ddd;">
    <tr style="background:#f5f7fa;"><th style="padding:10px; text-align:left; border-bottom:1px solid #ddd;">Name</th><td style="padding:10px; border-bottom:1px solid #ddd;">[APPOINTEE NAME]</td></tr>
    <tr><th style="padding:10px; text-align:left; border-bottom:1px solid #ddd;">Term Begins</th><td style="padding:10px; border-bottom:1px solid #ddd;">[DATE]</td></tr>
    <tr style="background:#f5f7fa;"><th style="padding:10px; text-align:left; border-bottom:1px solid #ddd;">Term Expires</th><td style="padding:10px; border-bottom:1px solid #ddd;">[DATE]</td></tr>
    <tr><th style="padding:10px; text-align:left;">Appointed By</th><td style="padding:10px;">Board of Selectmen, ${name}</td></tr>
  </table>
  <p style="font-size:14px; line-height:1.7;">This appointment is effective as of ${today}.</p>
  <p style="font-size:14px; margin-top:32px;">
    ___________________________<br/>Town Clerk<br/>${name}<br/>${today}
  </p>
${footer}`

    case 'press-release':
      return `${header}
  <p style="font-size:12px; color:#555; margin:0 0 4px;"><strong>FOR IMMEDIATE RELEASE</strong></p>
  <p style="font-size:12px; color:#555; margin:0 0 24px;">${today}</p>
  <p style="font-size:12px; color:#555; margin:0 0 24px;">
    <strong>Contact:</strong> [NAME], [TITLE] · [EMAIL] · [PHONE]
  </p>
  <h2 style="font-size:18px; font-weight:700; margin:0 0 20px;">[HEADLINE]</h2>
  <p style="font-size:12px; color:#555; font-style:italic; margin:0 0 20px;">${townName}, MA — ${today}</p>
  <p style="font-size:14px; line-height:1.8;">[LEAD PARAGRAPH — summarize the most important information in the first sentence.]</p>
  <p style="font-size:14px; line-height:1.8;">[SUPPORTING DETAIL]</p>
  <p style="font-size:14px; line-height:1.8;">[QUOTE FROM OFFICIAL]</p>
  <p style="font-size:14px; line-height:1.8;">[ADDITIONAL CONTEXT / NEXT STEPS]</p>
  <p style="font-size:14px; text-align:center; margin-top:32px;">###</p>
  <p style="font-size:12px; color:#555; margin-top:16px;"><em>About the ${name}: [Brief description of the town and its government structure.]</em></p>
${footer}`

    case 'annual-report-cover':
      return `${header}
  <div style="text-align:center; margin:40px 0;">
    <h2 style="font-size:26px; font-weight:700; letter-spacing:1px; color:#1e3a5f; margin:0 0 8px;">ANNUAL REPORT</h2>
    <h3 style="font-size:18px; font-weight:400; color:#555; margin:0 0 32px;">Fiscal Year ${fy}</h3>
    <div style="width:80px; height:3px; background:#1e3a5f; margin:0 auto 32px;"></div>
    <p style="font-size:15px; color:#333; line-height:1.8;">
      Prepared by the Office of the Town Clerk<br/>
      ${name}<br/>
      ${townCounty} County, Commonwealth of Massachusetts
    </p>
  </div>
  <hr style="border:none; border-top:1px solid #ddd; margin:40px 0;"/>
  <h3 style="font-size:15px; font-weight:700; margin:0 0 16px;">MESSAGE FROM THE TOWN ADMINISTRATOR</h3>
  <p style="font-size:14px; line-height:1.8;">
    On behalf of the Town of ${townName}, I am pleased to present the Annual Report for Fiscal Year ${fy}.
    This report reflects the work of our dedicated town employees and elected officials who serve the residents of ${townName} every day.
  </p>
  <p style="font-size:14px; line-height:1.8;">[CONTINUE WITH HIGHLIGHTS OF THE YEAR, KEY ACCOMPLISHMENTS, AND OUTLOOK]</p>
  <p style="font-size:14px; margin-top:32px;">
    Respectfully submitted,<br/><br/>
    ___________________________<br/>Town Administrator<br/>${name}
  </p>
${footer}`
  }
}

// ── DocPreviewModal component ─────────────────────────────────────────────────

export function DocPreviewModal({
  doc, onClose, onSaveToVault,
}: {
  doc: { type: DocType; label: string; content: string } | null
  onClose: () => void
  onSaveToVault: (content: string, label: string) => void
}) {
  if (!doc) return null
  return (
    <Dialog open onOpenChange={onClose}>
      <DialogContent className="max-w-3xl h-[90vh] flex flex-col p-0 gap-0">
        <DialogHeader className="px-4 pt-4 pb-3 border-b flex-shrink-0">
          <DialogTitle className="text-base">{doc.label}</DialogTitle>
          <div className="flex gap-2 mt-2">
            <Button size="sm" variant="outline" className="h-7 text-xs gap-1"
              onClick={() => { window.print() }}>
              <Printer size={13} /> Print
            </Button>
            <Button size="sm" variant="outline" className="h-7 text-xs gap-1"
              onClick={() => { navigator.clipboard.writeText(doc.content); toast.success('Copied to clipboard') }}>
              <Copy size={13} /> Copy HTML
            </Button>
            <Button size="sm" className="h-7 text-xs gap-1"
              onClick={() => onSaveToVault(doc.content, doc.label)}>
              <CloudArrowUp size={13} /> Save to Vault
            </Button>
          </div>
        </DialogHeader>
        <div className="flex-1 min-h-0 overflow-auto p-4 bg-white dark:bg-neutral-900">
          <div
            className="prose prose-sm max-w-none"
            dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(doc.content) }}
          />
        </div>
      </DialogContent>
    </Dialog>
  )
}
