/**
 * Massachusetts DOR municipality reference table.
 * DOR codes are the official identifiers used by Division of Local Services.
 * 351 municipalities — Worcester County subset highlighted for Phase 1.
 */

export interface Municipality {
  name: string;       // Official DLS name (must match iclMuni POST field exactly)
  dorCode: number;    // DOR numeric code
  county: string;
  population?: number;
}

/** Worcester County municipalities (Phase 1 target). */
export const WORCESTER_COUNTY: Municipality[] = [
  { name: "Ashburnham",       dorCode: 260, county: "Worcester" },
  { name: "Athol",            dorCode: 261, county: "Worcester" },
  { name: "Auburn",           dorCode: 262, county: "Worcester" },
  { name: "Barre",            dorCode: 263, county: "Worcester" },
  { name: "Berlin",           dorCode: 264, county: "Worcester" },
  { name: "Blackstone",       dorCode: 265, county: "Worcester" },
  { name: "Bolton",           dorCode: 266, county: "Worcester" },
  { name: "Boylston",         dorCode: 267, county: "Worcester" },
  { name: "Brookfield",       dorCode: 268, county: "Worcester" },
  { name: "Charlton",         dorCode: 269, county: "Worcester" },
  { name: "Clinton",          dorCode: 270, county: "Worcester" },
  { name: "Douglas",          dorCode: 271, county: "Worcester" },
  { name: "Dudley",           dorCode: 272, county: "Worcester" },
  { name: "East Brookfield",  dorCode: 273, county: "Worcester" },
  { name: "Fitchburg",        dorCode: 274, county: "Worcester" },
  { name: "Gardner",          dorCode: 275, county: "Worcester" },
  { name: "Grafton",          dorCode: 276, county: "Worcester" },
  { name: "Hardwick",         dorCode: 277, county: "Worcester" },
  { name: "Harvard",          dorCode: 278, county: "Worcester" },
  { name: "Holden",           dorCode: 279, county: "Worcester" },
  { name: "Hopedale",         dorCode: 280, county: "Worcester" },
  { name: "Hubbardston",      dorCode: 281, county: "Worcester" },
  { name: "Lancaster",        dorCode: 282, county: "Worcester" },
  { name: "Leicester",        dorCode: 283, county: "Worcester" },
  { name: "Leominster",       dorCode: 284, county: "Worcester" },
  { name: "Lunenburg",        dorCode: 285, county: "Worcester" },
  { name: "Mendon",           dorCode: 286, county: "Worcester" },
  { name: "Milford",          dorCode: 287, county: "Worcester" },
  { name: "Millbury",         dorCode: 288, county: "Worcester" },
  { name: "Millville",        dorCode: 289, county: "Worcester" },
  { name: "New Braintree",    dorCode: 290, county: "Worcester" },
  { name: "North Brookfield", dorCode: 291, county: "Worcester" },
  { name: "Northborough",     dorCode: 292, county: "Worcester" },
  { name: "Northbridge",      dorCode: 293, county: "Worcester" },
  { name: "Oakham",           dorCode: 294, county: "Worcester" },
  { name: "Oxford",           dorCode: 295, county: "Worcester" },
  { name: "Paxton",           dorCode: 296, county: "Worcester" },
  { name: "Phillipston",      dorCode: 297, county: "Worcester" },
  { name: "Princeton",        dorCode: 298, county: "Worcester" },
  { name: "Royalston",        dorCode: 299, county: "Worcester" },
  { name: "Rutland",          dorCode: 300, county: "Worcester" },
  { name: "Shrewsbury",       dorCode: 301, county: "Worcester" },
  { name: "Southborough",     dorCode: 302, county: "Worcester" },
  { name: "Southbridge",      dorCode: 303, county: "Worcester" },
  { name: "Spencer",          dorCode: 304, county: "Worcester" },
  { name: "Sterling",         dorCode: 305, county: "Worcester" },
  { name: "Stow",             dorCode: 306, county: "Worcester" },
  { name: "Sturbridge",       dorCode: 307, county: "Worcester" },
  { name: "Sutton",           dorCode: 308, county: "Worcester" },
  { name: "Templeton",        dorCode: 309, county: "Worcester" },
  { name: "Upton",            dorCode: 310, county: "Worcester" },
  { name: "Uxbridge",         dorCode: 311, county: "Worcester" },
  { name: "Warren",           dorCode: 312, county: "Worcester" },
  { name: "Webster",          dorCode: 313, county: "Worcester" },
  { name: "West Boylston",    dorCode: 314, county: "Worcester" },
  { name: "West Brookfield",  dorCode: 315, county: "Worcester" },
  { name: "Westborough",      dorCode: 316, county: "Worcester" },
  { name: "Westminster",      dorCode: 317, county: "Worcester" },
  { name: "Winchendon",       dorCode: 318, county: "Worcester" },
  { name: "Worcester",        dorCode: 319, county: "Worcester" },
];

// Complete DOR code lookup — add other counties as needed
export const ALL_MUNICIPALITIES: Municipality[] = [
  ...WORCESTER_COUNTY,
  // Additional counties can be appended here
];

export function findByName(name: string): Municipality | undefined {
  const lower = name.toLowerCase();
  return ALL_MUNICIPALITIES.find((m) => m.name.toLowerCase() === lower);
}

export function findByDorCode(code: number): Municipality | undefined {
  return ALL_MUNICIPALITIES.find((m) => m.dorCode === code);
}

/** Return municipalities in the same county, excluding the queried town. */
export function getPeers(name: string): Municipality[] {
  const target = findByName(name);
  if (!target) return [];
  return ALL_MUNICIPALITIES.filter(
    (m) => m.county === target.county && m.name !== target.name
  );
}

/** All 351 Massachusetts municipalities — sourced from MA DLS. */
export const ALL_MA_MUNICIPALITIES: Municipality[] = [
  { name: "Barnstable", dorCode: 1, county: "Barnstable", population: 45193 },
  { name: "Bourne", dorCode: 2, county: "Barnstable", population: 19754 },
  { name: "Brewster", dorCode: 3, county: "Barnstable", population: 9750 },
  { name: "Chatham", dorCode: 4, county: "Barnstable", population: 6211 },
  { name: "Dennis", dorCode: 5, county: "Barnstable", population: 14207 },
  { name: "Eastham", dorCode: 6, county: "Barnstable", population: 4956 },
  { name: "Falmouth", dorCode: 7, county: "Barnstable", population: 31531 },
  { name: "Harwich", dorCode: 8, county: "Barnstable", population: 13073 },
  { name: "Mashpee", dorCode: 9, county: "Barnstable", population: 14006 },
  { name: "Orleans", dorCode: 10, county: "Barnstable", population: 5890 },
  { name: "Provincetown", dorCode: 11, county: "Barnstable", population: 2985 },
  { name: "Sandwich", dorCode: 12, county: "Barnstable", population: 20136 },
  { name: "Truro", dorCode: 13, county: "Barnstable", population: 1970 },
  { name: "Wellfleet", dorCode: 14, county: "Barnstable", population: 2749 },
  { name: "Yarmouth", dorCode: 15, county: "Barnstable", population: 24807 },
  { name: "Adams", dorCode: 16, county: "Berkshire", population: 7725 },
  { name: "Alford", dorCode: 17, county: "Berkshire", population: 497 },
  { name: "Becket", dorCode: 18, county: "Berkshire", population: 1700 },
  { name: "Cheshire", dorCode: 19, county: "Berkshire", population: 3149 },
  { name: "Clarksburg", dorCode: 20, county: "Berkshire", population: 1678 },
  { name: "Dalton", dorCode: 21, county: "Berkshire", population: 6674 },
  { name: "Egremont", dorCode: 22, county: "Berkshire", population: 1234 },
  { name: "Florida", dorCode: 23, county: "Berkshire", population: 706 },
  { name: "Great Barrington", dorCode: 24, county: "Berkshire", population: 7159 },
  { name: "Hancock", dorCode: 25, county: "Berkshire", population: 759 },
  { name: "Hinsdale", dorCode: 26, county: "Berkshire", population: 1919 },
  { name: "Lanesborough", dorCode: 27, county: "Berkshire", population: 3087 },
  { name: "Lee", dorCode: 28, county: "Berkshire", population: 5799 },
  { name: "Lenox", dorCode: 29, county: "Berkshire", population: 4935 },
  { name: "Monterey", dorCode: 30, county: "Berkshire", population: 952 },
  { name: "Mount Washington", dorCode: 31, county: "Berkshire", population: 168 },
  { name: "New Ashford", dorCode: 32, county: "Berkshire", population: 232 },
  { name: "New Marlborough", dorCode: 33, county: "Berkshire", population: 1485 },
  { name: "North Adams", dorCode: 34, county: "Berkshire", population: 12961 },
  { name: "Otis", dorCode: 35, county: "Berkshire", population: 1627 },
  { name: "Peru", dorCode: 36, county: "Berkshire", population: 902 },
  { name: "Pittsfield", dorCode: 37, county: "Berkshire", population: 42142 },
  { name: "Richmond", dorCode: 38, county: "Berkshire", population: 1529 },
  { name: "Sandisfield", dorCode: 39, county: "Berkshire", population: 876 },
  { name: "Savoy", dorCode: 40, county: "Berkshire", population: 663 },
  { name: "Sheffield", dorCode: 41, county: "Berkshire", population: 3257 },
  { name: "Stockbridge", dorCode: 42, county: "Berkshire", population: 1942 },
  { name: "Tyringham", dorCode: 43, county: "Berkshire", population: 329 },
  { name: "Washington", dorCode: 44, county: "Berkshire", population: 553 },
  { name: "West Stockbridge", dorCode: 45, county: "Berkshire", population: 1271 },
  { name: "Williamstown", dorCode: 46, county: "Berkshire", population: 7635 },
  { name: "Windsor", dorCode: 47, county: "Berkshire", population: 855 },
  { name: "Acushnet", dorCode: 48, county: "Bristol", population: 10303 },
  { name: "Attleboro", dorCode: 49, county: "Bristol", population: 45273 },
  { name: "Berkley", dorCode: 50, county: "Bristol", population: 6567 },
  { name: "Dartmouth", dorCode: 51, county: "Bristol", population: 34032 },
  { name: "Dighton", dorCode: 52, county: "Bristol", population: 7717 },
  { name: "Easton", dorCode: 53, county: "Bristol", population: 24272 },
  { name: "Fairhaven", dorCode: 54, county: "Bristol", population: 16132 },
  { name: "Fall River", dorCode: 55, county: "Bristol", population: 94942 },
  { name: "Freetown", dorCode: 56, county: "Bristol", population: 9399 },
  { name: "Mansfield", dorCode: 57, county: "Bristol", population: 24145 },
  { name: "New Bedford", dorCode: 58, county: "Bristol", population: 101079 },
  { name: "North Attleborough", dorCode: 59, county: "Bristol", population: 29732 },
  { name: "Norton", dorCode: 60, county: "Bristol", population: 19764 },
  { name: "Raynham", dorCode: 61, county: "Bristol", population: 13813 },
  { name: "Rehoboth", dorCode: 62, county: "Bristol", population: 11608 },
  { name: "Seekonk", dorCode: 63, county: "Bristol", population: 15541 },
  { name: "Somerset", dorCode: 64, county: "Bristol", population: 18165 },
  { name: "Swansea", dorCode: 65, county: "Bristol", population: 16132 },
  { name: "Taunton", dorCode: 66, county: "Bristol", population: 57464 },
  { name: "Westport", dorCode: 67, county: "Bristol", population: 15532 },
  { name: "Aquinnah", dorCode: 68, county: "Dukes", population: 311 },
  { name: "Chilmark", dorCode: 69, county: "Dukes", population: 887 },
  { name: "Edgartown", dorCode: 70, county: "Dukes", population: 4498 },
  { name: "Gosnold", dorCode: 71, county: "Dukes", population: 75 },
  { name: "Oak Bluffs", dorCode: 72, county: "Dukes", population: 5374 },
  { name: "Tisbury", dorCode: 73, county: "Dukes", population: 4151 },
  { name: "West Tisbury", dorCode: 74, county: "Dukes", population: 3004 },
  { name: "Amesbury", dorCode: 75, county: "Essex", population: 17431 },
  { name: "Andover", dorCode: 76, county: "Essex", population: 35985 },
  { name: "Beverly", dorCode: 77, county: "Essex", population: 43688 },
  { name: "Boxford", dorCode: 78, county: "Essex", population: 8032 },
  { name: "Danvers", dorCode: 79, county: "Essex", population: 27642 },
  { name: "Essex", dorCode: 80, county: "Essex", population: 3584 },
  { name: "Georgetown", dorCode: 81, county: "Essex", population: 7981 },
  { name: "Gloucester", dorCode: 82, county: "Essex", population: 30273 },
  { name: "Groveland", dorCode: 83, county: "Essex", population: 6893 },
  { name: "Hamilton", dorCode: 84, county: "Essex", population: 7764 },
  { name: "Haverhill", dorCode: 85, county: "Essex", population: 65111 },
  { name: "Ipswich", dorCode: 86, county: "Essex", population: 13785 },
  { name: "Lawrence", dorCode: 87, county: "Essex", population: 80376 },
  { name: "Lynn", dorCode: 88, county: "Essex", population: 94299 },
  { name: "Lynnfield", dorCode: 89, county: "Essex", population: 12680 },
  { name: "Manchester", dorCode: 90, county: "Essex", population: 5783 },
  { name: "Marblehead", dorCode: 91, county: "Essex", population: 20339 },
  { name: "Merrimac", dorCode: 92, county: "Essex", population: 7145 },
  { name: "Methuen", dorCode: 93, county: "Essex", population: 50742 },
  { name: "Middleton", dorCode: 94, county: "Essex", population: 9874 },
  { name: "Nahant", dorCode: 95, county: "Essex", population: 3352 },
  { name: "Newbury", dorCode: 96, county: "Essex", population: 6936 },
  { name: "Newburyport", dorCode: 97, county: "Essex", population: 18289 },
  { name: "North Andover", dorCode: 98, county: "Essex", population: 31109 },
  { name: "Peabody", dorCode: 99, county: "Essex", population: 54546 },
  { name: "Rockport", dorCode: 100, county: "Essex", population: 7609 },
  { name: "Rowley", dorCode: 101, county: "Essex", population: 6475 },
  { name: "Salem", dorCode: 102, county: "Essex", population: 44672 },
  { name: "Salisbury", dorCode: 103, county: "Essex", population: 9227 },
  { name: "Saugus", dorCode: 104, county: "Essex", population: 28482 },
  { name: "Swampscott", dorCode: 105, county: "Essex", population: 14913 },
  { name: "Topsfield", dorCode: 106, county: "Essex", population: 6266 },
  { name: "Wenham", dorCode: 107, county: "Essex", population: 4920 },
  { name: "West Newbury", dorCode: 108, county: "Essex", population: 4527 },
  { name: "Ashfield", dorCode: 109, county: "Franklin", population: 1742 },
  { name: "Bernardston", dorCode: 110, county: "Franklin", population: 2102 },
  { name: "Buckland", dorCode: 111, county: "Franklin", population: 1883 },
  { name: "Charlemont", dorCode: 112, county: "Franklin", population: 1249 },
  { name: "Colrain", dorCode: 113, county: "Franklin", population: 1672 },
  { name: "Conway", dorCode: 114, county: "Franklin", population: 1896 },
  { name: "Deerfield", dorCode: 115, county: "Franklin", population: 5103 },
  { name: "Erving", dorCode: 116, county: "Franklin", population: 1713 },
  { name: "Gill", dorCode: 117, county: "Franklin", population: 1596 },
  { name: "Greenfield", dorCode: 118, county: "Franklin", population: 17456 },
  { name: "Hawley", dorCode: 119, county: "Franklin", population: 336 },
  { name: "Heath", dorCode: 120, county: "Franklin", population: 688 },
  { name: "Leverett", dorCode: 121, county: "Franklin", population: 1917 },
  { name: "Leyden", dorCode: 122, county: "Franklin", population: 699 },
  { name: "Monroe", dorCode: 123, county: "Franklin", population: 105 },
  { name: "Montague", dorCode: 124, county: "Franklin", population: 8432 },
  { name: "New Salem", dorCode: 125, county: "Franklin", population: 990 },
  { name: "Northfield", dorCode: 126, county: "Franklin", population: 2923 },
  { name: "Orange", dorCode: 127, county: "Franklin", population: 7596 },
  { name: "Rowe", dorCode: 128, county: "Franklin", population: 399 },
  { name: "Shelburne", dorCode: 129, county: "Franklin", population: 1873 },
  { name: "Shutesbury", dorCode: 130, county: "Franklin", population: 1810 },
  { name: "Sunderland", dorCode: 131, county: "Franklin", population: 3675 },
  { name: "Warwick", dorCode: 132, county: "Franklin", population: 778 },
  { name: "Wendell", dorCode: 133, county: "Franklin", population: 955 },
  { name: "Whately", dorCode: 134, county: "Franklin", population: 1599 },
  { name: "Agawam", dorCode: 135, county: "Hampden", population: 28438 },
  { name: "Blandford", dorCode: 136, county: "Hampden", population: 1263 },
  { name: "Brimfield", dorCode: 137, county: "Hampden", population: 3613 },
  { name: "Chester", dorCode: 138, county: "Hampden", population: 1337 },
  { name: "Chicopee", dorCode: 139, county: "Hampden", population: 56673 },
  { name: "East Longmeadow", dorCode: 140, county: "Hampden", population: 16053 },
  { name: "Granville", dorCode: 141, county: "Hampden", population: 1617 },
  { name: "Hampden", dorCode: 142, county: "Hampden", population: 5171 },
  { name: "Holland", dorCode: 143, county: "Hampden", population: 2467 },
  { name: "Holyoke", dorCode: 144, county: "Hampden", population: 38238 },
  { name: "Longmeadow", dorCode: 145, county: "Hampden", population: 15784 },
  { name: "Ludlow", dorCode: 146, county: "Hampden", population: 21479 },
  { name: "Monson", dorCode: 147, county: "Hampden", population: 8596 },
  { name: "Montgomery", dorCode: 148, county: "Hampden", population: 834 },
  { name: "Palmer", dorCode: 149, county: "Hampden", population: 12148 },
  { name: "Russell", dorCode: 150, county: "Hampden", population: 1790 },
  { name: "Southwick", dorCode: 151, county: "Hampden", population: 9502 },
  { name: "Springfield", dorCode: 152, county: "Hampden", population: 153606 },
  { name: "Tolland", dorCode: 153, county: "Hampden", population: 456 },
  { name: "Wales", dorCode: 154, county: "Hampden", population: 1788 },
  { name: "West Springfield", dorCode: 155, county: "Hampden", population: 28391 },
  { name: "Westfield", dorCode: 156, county: "Hampden", population: 41301 },
  { name: "Wilbraham", dorCode: 157, county: "Hampden", population: 22085 },
  { name: "Amherst", dorCode: 158, county: "Hampshire", population: 37819 },
  { name: "Belchertown", dorCode: 159, county: "Hampshire", population: 14649 },
  { name: "Chesterfield", dorCode: 160, county: "Hampshire", population: 1258 },
  { name: "Cummington", dorCode: 161, county: "Hampshire", population: 896 },
  { name: "Easthampton", dorCode: 162, county: "Hampshire", population: 16053 },
  { name: "Goshen", dorCode: 163, county: "Hampshire", population: 1043 },
  { name: "Granby", dorCode: 164, county: "Hampshire", population: 5952 },
  { name: "Hadley", dorCode: 165, county: "Hampshire", population: 5250 },
  { name: "Hatfield", dorCode: 166, county: "Hampshire", population: 3279 },
  { name: "Huntington", dorCode: 167, county: "Hampshire", population: 1984 },
  { name: "Middlefield", dorCode: 168, county: "Hampshire", population: 436 },
  { name: "Northampton", dorCode: 169, county: "Hampshire", population: 28549 },
  { name: "Pelham", dorCode: 170, county: "Hampshire", population: 1329 },
  { name: "Plainfield", dorCode: 171, county: "Hampshire", population: 621 },
  { name: "South Hadley", dorCode: 172, county: "Hampshire", population: 17514 },
  { name: "Southampton", dorCode: 173, county: "Hampshire", population: 5846 },
  { name: "Ware", dorCode: 174, county: "Hampshire", population: 9839 },
  { name: "Westhampton", dorCode: 175, county: "Hampshire", population: 1642 },
  { name: "Williamsburg", dorCode: 176, county: "Hampshire", population: 2427 },
  { name: "Worthington", dorCode: 177, county: "Hampshire", population: 1241 },
  { name: "Acton", dorCode: 178, county: "Middlesex", population: 23389 },
  { name: "Arlington", dorCode: 179, county: "Middlesex", population: 45531 },
  { name: "Ashby", dorCode: 180, county: "Middlesex", population: 3057 },
  { name: "Ashland", dorCode: 181, county: "Middlesex", population: 17179 },
  { name: "Ayer", dorCode: 182, county: "Middlesex", population: 7664 },
  { name: "Bedford", dorCode: 183, county: "Middlesex", population: 13820 },
  { name: "Belmont", dorCode: 184, county: "Middlesex", population: 24729 },
  { name: "Billerica", dorCode: 185, county: "Middlesex", population: 43140 },
  { name: "Boxborough", dorCode: 186, county: "Middlesex", population: 5820 },
  { name: "Burlington", dorCode: 187, county: "Middlesex", population: 27115 },
  { name: "Cambridge", dorCode: 188, county: "Middlesex", population: 118403 },
  { name: "Carlisle", dorCode: 189, county: "Middlesex", population: 4852 },
  { name: "Chelmsford", dorCode: 190, county: "Middlesex", population: 37103 },
  { name: "Concord", dorCode: 191, county: "Middlesex", population: 20001 },
  { name: "Dracut", dorCode: 192, county: "Middlesex", population: 32545 },
  { name: "Dunstable", dorCode: 193, county: "Middlesex", population: 3179 },
  { name: "Everett", dorCode: 194, county: "Middlesex", population: 46451 },
  { name: "Framingham", dorCode: 195, county: "Middlesex", population: 72362 },
  { name: "Groton", dorCode: 196, county: "Middlesex", population: 11060 },
  { name: "Holliston", dorCode: 197, county: "Middlesex", population: 14844 },
  { name: "Hopkinton", dorCode: 198, county: "Middlesex", population: 17317 },
  { name: "Hudson", dorCode: 199, county: "Middlesex", population: 19467 },
  { name: "Lexington", dorCode: 200, county: "Middlesex", population: 32974 },
  { name: "Lincoln", dorCode: 201, county: "Middlesex", population: 6362 },
  { name: "Littleton", dorCode: 202, county: "Middlesex", population: 9924 },
  { name: "Lowell", dorCode: 203, county: "Middlesex", population: 113113 },
  { name: "Malden", dorCode: 204, county: "Middlesex", population: 60470 },
  { name: "Marlborough", dorCode: 205, county: "Middlesex", population: 39984 },
  { name: "Maynard", dorCode: 206, county: "Middlesex", population: 10013 },
  { name: "Medford", dorCode: 207, county: "Middlesex", population: 57341 },
  { name: "Melrose", dorCode: 208, county: "Middlesex", population: 27912 },
  { name: "Natick", dorCode: 209, county: "Middlesex", population: 35152 },
  { name: "Newton", dorCode: 210, county: "Middlesex", population: 88923 },
  { name: "North Reading", dorCode: 211, county: "Middlesex", population: 15807 },
  { name: "Pepperell", dorCode: 212, county: "Middlesex", population: 11974 },
  { name: "Reading", dorCode: 213, county: "Middlesex", population: 25812 },
  { name: "Sherborn", dorCode: 214, county: "Middlesex", population: 4360 },
  { name: "Shirley", dorCode: 215, county: "Middlesex", population: 7074 },
  { name: "Somerville", dorCode: 216, county: "Middlesex", population: 81360 },
  { name: "Stoneham", dorCode: 217, county: "Middlesex", population: 23503 },
  { name: "Stow", dorCode: 218, county: "Middlesex", population: 7004 },
  { name: "Sudbury", dorCode: 219, county: "Middlesex", population: 18860 },
  { name: "Tewksbury", dorCode: 220, county: "Middlesex", population: 30713 },
  { name: "Townsend", dorCode: 221, county: "Middlesex", population: 9494 },
  { name: "Tyngsborough", dorCode: 222, county: "Middlesex", population: 11801 },
  { name: "Wakefield", dorCode: 223, county: "Middlesex", population: 27227 },
  { name: "Waltham", dorCode: 224, county: "Middlesex", population: 60632 },
  { name: "Watertown", dorCode: 225, county: "Middlesex", population: 35939 },
  { name: "Wayland", dorCode: 226, county: "Middlesex", population: 13100 },
  { name: "Westford", dorCode: 227, county: "Middlesex", population: 23692 },
  { name: "Weston", dorCode: 228, county: "Middlesex", population: 11973 },
  { name: "Wilmington", dorCode: 229, county: "Middlesex", population: 22768 },
  { name: "Winchester", dorCode: 230, county: "Middlesex", population: 22960 },
  { name: "Woburn", dorCode: 231, county: "Middlesex", population: 39034 },
  { name: "Nantucket", dorCode: 232, county: "Nantucket", population: 14255 },
  { name: "Avon", dorCode: 233, county: "Norfolk", population: 4356 },
  { name: "Bellingham", dorCode: 234, county: "Norfolk", population: 17009 },
  { name: "Braintree", dorCode: 235, county: "Norfolk", population: 37712 },
  { name: "Brookline", dorCode: 236, county: "Norfolk", population: 58732 },
  { name: "Canton", dorCode: 237, county: "Norfolk", population: 22561 },
  { name: "Cohasset", dorCode: 238, county: "Norfolk", population: 8899 },
  { name: "Dedham", dorCode: 239, county: "Norfolk", population: 24729 },
  { name: "Dover", dorCode: 240, county: "Norfolk", population: 5569 },
  { name: "Foxborough", dorCode: 241, county: "Norfolk", population: 17539 },
  { name: "Franklin", dorCode: 242, county: "Norfolk", population: 33794 },
  { name: "Holbrook", dorCode: 243, county: "Norfolk", population: 11036 },
  { name: "Medfield", dorCode: 244, county: "Norfolk", population: 12024 },
  { name: "Medway", dorCode: 245, county: "Norfolk", population: 13125 },
  { name: "Millis", dorCode: 246, county: "Norfolk", population: 7685 },
  { name: "Milton", dorCode: 247, county: "Norfolk", population: 27003 },
  { name: "Needham", dorCode: 248, county: "Norfolk", population: 30004 },
  { name: "Norfolk", dorCode: 249, county: "Norfolk", population: 11227 },
  { name: "Norwood", dorCode: 250, county: "Norfolk", population: 28602 },
  { name: "Plainville", dorCode: 251, county: "Norfolk", population: 8785 },
  { name: "Quincy", dorCode: 252, county: "Norfolk", population: 101636 },
  { name: "Randolph", dorCode: 253, county: "Norfolk", population: 34983 },
  { name: "Sharon", dorCode: 254, county: "Norfolk", population: 18498 },
  { name: "Stoughton", dorCode: 255, county: "Norfolk", population: 28143 },
  { name: "Walpole", dorCode: 256, county: "Norfolk", population: 24635 },
  { name: "Wellesley", dorCode: 257, county: "Norfolk", population: 28220 },
  { name: "Westwood", dorCode: 258, county: "Norfolk", population: 15560 },
  { name: "Weymouth", dorCode: 259, county: "Norfolk", population: 53743 },
  { name: "Wrentham", dorCode: 260, county: "Norfolk", population: 11285 },
  { name: "Ashburnham", dorCode: 261, county: "Worcester", population: 5856 },
  { name: "Athol", dorCode: 262, county: "Worcester", population: 11584 },
  { name: "Auburn", dorCode: 263, county: "Worcester", population: 16971 },
  { name: "Barre", dorCode: 264, county: "Worcester", population: 5559 },
  { name: "Berlin", dorCode: 265, county: "Worcester", population: 3077 },
  { name: "Blackstone", dorCode: 266, county: "Worcester", population: 9026 },
  { name: "Bolton", dorCode: 267, county: "Worcester", population: 5139 },
  { name: "Boylston", dorCode: 268, county: "Worcester", population: 4563 },
  { name: "Brookfield", dorCode: 269, county: "Worcester", population: 3340 },
  { name: "Charlton", dorCode: 270, county: "Worcester", population: 13058 },
  { name: "Clinton", dorCode: 271, county: "Worcester", population: 13844 },
  { name: "Douglas", dorCode: 272, county: "Worcester", population: 8942 },
  { name: "Dudley", dorCode: 273, county: "Worcester", population: 11546 },
  { name: "East Brookfield", dorCode: 274, county: "Worcester", population: 2236 },
  { name: "Fitchburg", dorCode: 275, county: "Worcester", population: 40759 },
  { name: "Gardner", dorCode: 276, county: "Worcester", population: 20892 },
  { name: "Grafton", dorCode: 277, county: "Worcester", population: 19176 },
  { name: "Hardwick", dorCode: 278, county: "Worcester", population: 2926 },
  { name: "Harvard", dorCode: 279, county: "Worcester", population: 6533 },
  { name: "Holden", dorCode: 280, county: "Worcester", population: 18470 },
  { name: "Hopedale", dorCode: 281, county: "Worcester", population: 5940 },
  { name: "Hubbardston", dorCode: 282, county: "Worcester", population: 4382 },
  { name: "Lancaster", dorCode: 283, county: "Worcester", population: 8055 },
  { name: "Leicester", dorCode: 284, county: "Worcester", population: 11287 },
  { name: "Leominster", dorCode: 285, county: "Worcester", population: 41303 },
  { name: "Lunenburg", dorCode: 286, county: "Worcester", population: 11099 },
  { name: "Mendon", dorCode: 287, county: "Worcester", population: 6019 },
  { name: "Milford", dorCode: 288, county: "Worcester", population: 27999 },
  { name: "Millbury", dorCode: 289, county: "Worcester", population: 13261 },
  { name: "Millville", dorCode: 290, county: "Worcester", population: 3081 },
  { name: "New Braintree", dorCode: 291, county: "Worcester", population: 1139 },
  { name: "North Brookfield", dorCode: 292, county: "Worcester", population: 4725 },
  { name: "Northborough", dorCode: 293, county: "Worcester", population: 15707 },
  { name: "Northbridge", dorCode: 294, county: "Worcester", population: 16272 },
  { name: "Oakham", dorCode: 295, county: "Worcester", population: 1859 },
  { name: "Oxford", dorCode: 296, county: "Worcester", population: 13709 },
  { name: "Paxton", dorCode: 297, county: "Worcester", population: 4795 },
  { name: "Phillipston", dorCode: 298, county: "Worcester", population: 1711 },
  { name: "Princeton", dorCode: 299, county: "Worcester", population: 3416 },
  { name: "Royalston", dorCode: 300, county: "Worcester", population: 1254 },
  { name: "Rutland", dorCode: 301, county: "Worcester", population: 8082 },
  { name: "Shrewsbury", dorCode: 302, county: "Worcester", population: 37444 },
  { name: "Southborough", dorCode: 303, county: "Worcester", population: 9767 },
  { name: "Southbridge", dorCode: 304, county: "Worcester", population: 16719 },
  { name: "Spencer", dorCode: 305, county: "Worcester", population: 11837 },
  { name: "Sterling", dorCode: 306, county: "Worcester", population: 8102 },
  { name: "Stow", dorCode: 307, county: "Worcester", population: 7090 },
  { name: "Sturbridge", dorCode: 308, county: "Worcester", population: 9247 },
  { name: "Sutton", dorCode: 309, county: "Worcester", population: 9503 },
  { name: "Templeton", dorCode: 310, county: "Worcester", population: 8096 },
  { name: "Upton", dorCode: 311, county: "Worcester", population: 8003 },
  { name: "Uxbridge", dorCode: 312, county: "Worcester", population: 14511 },
  { name: "Warren", dorCode: 313, county: "Worcester", population: 5142 },
  { name: "Webster", dorCode: 314, county: "Worcester", population: 16767 },
  { name: "West Boylston", dorCode: 315, county: "Worcester", population: 7880 },
  { name: "West Brookfield", dorCode: 316, county: "Worcester", population: 3892 },
  { name: "Westborough", dorCode: 317, county: "Worcester", population: 19051 },
  { name: "Westminster", dorCode: 318, county: "Worcester", population: 7863 },
  { name: "Winchendon", dorCode: 319, county: "Worcester", population: 10247 },
  { name: "Worcester", dorCode: 320, county: "Worcester", population: 206518 },
  { name: "Abington", dorCode: 321, county: "Plymouth", population: 16846 },
  { name: "Bridgewater", dorCode: 322, county: "Plymouth", population: 27002 },
  { name: "Brockton", dorCode: 323, county: "Plymouth", population: 105643 },
  { name: "Carver", dorCode: 324, county: "Plymouth", population: 12056 },
  { name: "Duxbury", dorCode: 325, county: "Plymouth", population: 15774 },
  { name: "East Bridgewater", dorCode: 326, county: "Plymouth", population: 14265 },
  { name: "Halifax", dorCode: 327, county: "Plymouth", population: 7873 },
  { name: "Hanover", dorCode: 328, county: "Plymouth", population: 14588 },
  { name: "Hanson", dorCode: 329, county: "Plymouth", population: 10209 },
  { name: "Hingham", dorCode: 330, county: "Plymouth", population: 23117 },
  { name: "Hull", dorCode: 331, county: "Plymouth", population: 10427 },
  { name: "Kingston", dorCode: 332, county: "Plymouth", population: 13934 },
  { name: "Lakeville", dorCode: 333, county: "Plymouth", population: 11922 },
  { name: "Marion", dorCode: 334, county: "Plymouth", population: 5057 },
  { name: "Marshfield", dorCode: 335, county: "Plymouth", population: 25132 },
  { name: "Mattapoisett", dorCode: 336, county: "Plymouth", population: 6268 },
  { name: "Middleborough", dorCode: 337, county: "Plymouth", population: 24048 },
  { name: "Norwell", dorCode: 338, county: "Plymouth", population: 10659 },
  { name: "Pembroke", dorCode: 339, county: "Plymouth", population: 18547 },
  { name: "Plymouth", dorCode: 340, county: "Plymouth", population: 61217 },
  { name: "Plympton", dorCode: 341, county: "Plymouth", population: 3204 },
  { name: "Rochester", dorCode: 342, county: "Plymouth", population: 5508 },
  { name: "Rockland", dorCode: 343, county: "Plymouth", population: 17489 },
  { name: "Scituate", dorCode: 344, county: "Plymouth", population: 18874 },
  { name: "Wareham", dorCode: 345, county: "Plymouth", population: 23132 },
  { name: "West Bridgewater", dorCode: 346, county: "Plymouth", population: 6916 },
  { name: "Whitman", dorCode: 347, county: "Plymouth", population: 15279 },
  { name: "Boston", dorCode: 348, county: "Suffolk", population: 675647 },
  { name: "Chelsea", dorCode: 349, county: "Suffolk", population: 40111 },
  { name: "Revere", dorCode: 350, county: "Suffolk", population: 53756 },
  { name: "Winthrop", dorCode: 351, county: "Suffolk", population: 18127 },
];
