// @pj/pipeline — the V1 synchronous spine, stage definitions.
// Source of truth: Issue #99 ("V1 runtime flow") + ops/v1/C0_DIAGNOSIS.md.
//
// C1 scope: model the spine end-to-end with stubbed stages. No rule packs,
// no holds, no connectors, no UI, no schema changes. Each stage is a pure
// function that takes the running context and returns a verdict. The runner
// (run.ts) walks them in order and writes ONE audit event proving it ran.

/**
 * The fourteen canon pipeline stages, in execution order. This list is the
 * literal spine from Issue #99. Stage names are stable identifiers used in
 * the Recordstream payload so a later phase can prove which stages ran.
 */
export const PIPELINE_STAGES = [
  'AUTH',
  'INPUT',
  'CAPTURE_NEW_ITEM',
  'FORMKEY_INTAKE',
  'API_ENRICHMENT',
  'VAULT_SCHEMA_RESOLVE',
  'ROUTE',
  'ACCESS_GATE',
  'SUBSTANCE_CHECK',
  'STATE_UPDATE_OR_HOLD',
  'INSTALLED_TOOLS_ACT',
  'FORMKEY_OUTPUT',
  'RECORDSTREAM',
  'RETENTION_ARCHIEVE',
] as const;

export type PipelineStage = (typeof PIPELINE_STAGES)[number];

/**
 * The proof vocabulary every branch must eventually write (Issue #99).
 * In C1 every stub stage returns `accepted`; later phases (C5–C8) introduce
 * `denied` / `held` / `approved` / `failed` / `output_generated` /
 * `retention_applied` as real verdicts sourced from rule packs and gates.
 */
export type StageOutcome =
  | 'accepted'
  | 'no_op'
  | 'denied'
  | 'held'
  | 'approved'
  | 'failed'
  | 'output_generated'
  | 'retention_applied';

/** Immutable input handed to the pipeline run. */
export interface PipelineInput {
  /** Triad pack id, e.g. `guestops.stay` (C0 canonical V1 triad). */
  pack: string;
  /** Tenant the run is scoped to. */
  tenant_id: string;
  /** Deployment the run is scoped to. */
  deployment_id: string;
  /** Authenticated actor reference (auth is NOT implemented in C1). */
  actor_ref?: string | null;
  /** Raw item payload that entered at INPUT. Opaque in C1. */
  item?: unknown;
}

/** Mutable context threaded through the stages as the spine runs. */
export interface PipelineContext extends PipelineInput {
  /** Canon version stamped onto the proof event. */
  canon_version: string;
  /** Per-run process identifier (generated by the runner). */
  process_id: string;
}

/** Result of a single stage. */
export interface StageResult {
  stage: PipelineStage;
  outcome: StageOutcome;
  /** Short human note — why this outcome. Kept terse for the proof payload. */
  note: string;
}

/** A stage is a pure function over the running context. */
export type StageFn = (ctx: PipelineContext) => StageResult;

/**
 * C1 stub: every stage accepts and passes the item along. The note records
 * what a real implementation of the stage will own, so the skeleton doubles
 * as a contract for C2+. No branching logic yet — that arrives with rule
 * packs (C3/C5), access gate + substance check (C7), and holds (C6).
 */
const STAGE_NOTES: Record<PipelineStage, string> = {
  AUTH: 'actor already authenticated upstream (Apple/Google/Microsoft); pass-through in C1',
  INPUT: 'raw item received at the spine entry',
  CAPTURE_NEW_ITEM: '+ New Item capture surface; classification deferred to C3+',
  FORMKEY_INTAKE: 'FormKey intake envelope; validation/consent deferred',
  API_ENRICHMENT: 'enrichment adapters are stubbed; real connectors are C4',
  VAULT_SCHEMA_RESOLVE: 'VAULT schema resolve; rule-pack lookup is C3/C5',
  ROUTE: 'route to CaseSpace target; routing table is C3',
  ACCESS_GATE: 'access gate open in C1; can() wiring is C7',
  SUBSTANCE_CHECK: 'substance check passes in C1; no silent discard rule is C7',
  STATE_UPDATE_OR_HOLD: 'state update only in C1; holds are first-class in C6',
  INSTALLED_TOOLS_ACT: 'installed tools no-op in C1; SYNCHRON8 dispatch is later',
  FORMKEY_OUTPUT: 'FormKey output render is stubbed; output engine is C8',
  RECORDSTREAM: 'Recordstream proof is written by the runner for the whole run',
  RETENTION_ARCHIEVE: 'retention/ARCHIEVE attach is stubbed; enforcement is C8',
};

/**
 * Build the ordered list of stage functions. Each is a stub that returns
 * `accepted`. Kept as a factory so C2+ can swap individual stages for real
 * implementations without changing the runner.
 */
export function buildStages(): StageFn[] {
  return PIPELINE_STAGES.map((stage): StageFn => {
    return (_ctx: PipelineContext): StageResult => ({
      stage,
      outcome: 'accepted',
      note: STAGE_NOTES[stage],
    });
  });
}
