#!/usr/bin/env node
/**
 * sync-brand — derive @pj/web's served brand assets from the canonical
 * `branding/` kit, so the app brand can't drift from the source of truth.
 *
 *   node scripts/sync-brand.mjs           # copy branding/* into apps/web
 *   node scripts/sync-brand.mjs --check   # CI: exit 1 if any copy is stale
 *
 * Canonical source : <repo>/branding/
 * Generated copies : apps/web/app/icon.svg, apps/web/app/apple-icon.svg,
 *                    apps/web/public/brand/*.svg   (DO NOT edit by hand)
 *
 * Mirrors the repo's sync-playbooks pattern (canonical source + --check drift).
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, resolve, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const brand = join(root, 'branding')
const web = join(root, 'apps', 'web')
const check = process.argv.includes('--check')

// source (relative to branding/) -> destination (relative to apps/web/)
const MAP = [
  ['mark/favicon.svg', 'app/icon.svg'],
  ['mark/favicon.svg', 'app/apple-icon.svg'],
  ['mark/puddlejumper-mark.svg', 'public/brand/puddlejumper-mark.svg'],
  ['mark/puddlejumper-mark-reverse.svg', 'public/brand/puddlejumper-mark-reverse.svg'],
  ['wordmark/puddlejumper-wordmark-tagline.svg', 'public/brand/puddlejumper-wordmark-tagline.svg'],
  ['wordmark/puddlejumper-wordmark-reverse.svg', 'public/brand/puddlejumper-wordmark-reverse.svg'],
  ['lockup/puddlejumper-horizontal.svg', 'public/brand/puddlejumper-horizontal.svg'],
  ['lockup/puddlejumper-stacked.svg', 'public/brand/puddlejumper-stacked.svg'],
  ['mascot/puddlejumper-duck-flat.svg', 'public/brand/puddlejumper-duck-flat.svg'],
]

const banner = (rel) =>
  `<!-- GENERATED by scripts/sync-brand.mjs from branding/${rel} — DO NOT EDIT. -->\n`

let stale = 0
for (const [src, dst] of MAP) {
  const srcPath = join(brand, src)
  const dstPath = join(web, dst)
  if (!existsSync(srcPath)) {
    console.error(`MISSING SOURCE  branding/${src}`)
    stale++
    continue
  }
  const want = banner(src) + readFileSync(srcPath, 'utf8')
  const have = existsSync(dstPath) ? readFileSync(dstPath, 'utf8') : null
  if (have === want) continue

  if (check) {
    console.error(`STALE  ${dst}  (run: node scripts/sync-brand.mjs)`)
    stale++
  } else {
    mkdirSync(dirname(dstPath), { recursive: true })
    writeFileSync(dstPath, want)
    console.log(`synced  ${dst}`)
  }
}

if (check && stale) {
  console.error(`\nbrand assets out of sync (${stale}). Run: node scripts/sync-brand.mjs`)
  process.exit(1)
}
if (!check) console.log(stale ? `\ndone with ${stale} missing source(s)` : 'brand assets in sync')
