import type { VaultDocFull, VaultEvent, VaultSignature, VaultVersion, VaultStatus, VaultClassification } from '@/services/pjApi'
import { STATUS_META, CLASS_META } from './vaultConstants'
import { fmtTime } from './vaultHelpers'
import { createLogger } from '@/lib/logger'

const logger = createLogger('generateAuditPack')

export async function generateAuditPack(
  doc: VaultDocFull,
  events: VaultEvent[],
  signatures: VaultSignature[],
  versions: VaultVersion[],
): Promise<void> {
  const hashBuf = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(doc.html + doc.css))
  const hashHex = Array.from(new Uint8Array(hashBuf)).map(b => b.toString(16).padStart(2, '0')).join('')
  const sm = STATUS_META[doc.status as VaultStatus]
  const cm = CLASS_META[doc.classification as VaultClassification]

  const evHtml = events.map(ev => {
    let detail = ''
    try {
      const d = JSON.parse(ev.details)
      if (ev.event_type === 'status_changed') detail = ` (${d.from} → ${d.to})`
      else if (ev.event_type === 'classified') detail = ` (${d.from} → ${d.to})`
    } catch (error) {
      logger.error('Failed to parse audit event details while generating HTML.', error, { eventId: ev.id, eventType: ev.event_type })
    }
    return `<tr><td>${fmtTime(ev.created_at)}</td><td>${ev.user_name || ev.user_id}</td><td style="text-transform:capitalize">${ev.event_type.replace('_', ' ')}${detail}</td></tr>`
  }).join('')

  const sigHtml = signatures.map(sig =>
    `<div style="border:1px solid #ccc;padding:1rem;border-radius:6px;margin:.5rem 0;background:#f9fef9">
      <strong>${sig.user_name}</strong>${sig.comment ? ` — "${sig.comment}"` : ''}<br/>
      <small style="color:#555">Signed: ${fmtTime(sig.created_at)} | Content fingerprint: #${sig.content_hash}</small>
    </div>`
  ).join('')

  const html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<title>Audit Pack — ${doc.name}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, sans-serif; color: #1a1a1a; background: #fff; }
  .cover { background: #0f172a; color: #fff; padding: 3rem 4rem; }
  .cover h1 { font-size: 2rem; margin-bottom: .5rem; }
  .cover .meta { opacity: .7; font-size: .9rem; }
  .badge { display: inline-block; padding: .25rem .75rem; border-radius: 999px; font-size: .8rem; font-weight: 600; margin: .25rem; }
  .doc-section { padding: 3rem 4rem; border-bottom: 2px solid #e2e8f0; }
  .gov-section { padding: 3rem 4rem; background: #f8fafc; }
  .gov-section h2 { font-size: 1.1rem; margin-bottom: 1.5rem; text-transform: uppercase; letter-spacing: .1em; color: #475569; }
  table { width: 100%; border-collapse: collapse; font-size: .9rem; }
  th { background: #e2e8f0; padding: .5rem .75rem; text-align: left; }
  td { padding: .5rem .75rem; border-bottom: 1px solid #e2e8f0; }
  .footer { text-align: center; padding: 2rem; font-size: .8rem; color: #94a3b8; border-top: 1px solid #e2e8f0; }
  .hash { font-family: monospace; background: #f1f5f9; padding: .2rem .4rem; border-radius: 4px; font-size: .85rem; }
  @media print { .cover { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
</style>
</head><body>
<div class="cover">
  <p style="opacity:.5;font-size:.8rem;letter-spacing:.15em;text-transform:uppercase;margin-bottom:1rem">PublicLogic Vault · Audit Pack</p>
  <h1>${doc.name}</h1>
  <p class="meta">Generated: ${fmtTime(Date.now())}</p>
  <div style="margin-top:1.5rem">
    <span class="badge" style="background:rgba(255,255,255,.15)">${sm.label}</span>
    <span class="badge" style="background:rgba(255,255,255,.15)">${cm.label}</span>
  </div>
</div>

<div class="doc-section">
  <style>${doc.css}</style>
  ${doc.html}
</div>

<div class="gov-section">
  <h2>Document Metadata</h2>
  <table>
    <tr><th>Field</th><th>Value</th></tr>
    <tr><td>Document ID</td><td class="hash">${doc.id}</td></tr>
    <tr><td>Status</td><td>${sm.label}</td></tr>
    <tr><td>Classification</td><td>${cm.label}</td></tr>
    <tr><td>Created</td><td>${fmtTime(doc.created_at)}</td></tr>
    <tr><td>Last Updated</td><td>${fmtTime(doc.updated_at)}</td></tr>
    <tr><td>Versions Saved</td><td>${versions.length}</td></tr>
    <tr><td>Content Fingerprint (SHA-256)</td><td class="hash">${hashHex}</td></tr>
  </table>

  ${signatures.length > 0 ? `<h2 style="margin-top:2rem">Signatures (${signatures.length})</h2>${sigHtml}` : ''}

  <h2 style="margin-top:2rem">Complete Audit Trail (${events.length} events)</h2>
  <table>
    <thead><tr><th>Time</th><th>User</th><th>Action</th></tr></thead>
    <tbody>${evHtml}</tbody>
  </table>
</div>

<div class="footer">
  This Audit Pack was generated by PublicLogic Vault and represents the complete governance record for this document.<br/>
  Content fingerprint: <span class="hash">${hashHex.slice(0, 16)}…</span> · Verified at ${fmtTime(Date.now())}
</div>
</body></html>`

  const blob = new Blob([html], { type: 'text/html' })
  const a = document.createElement('a')
  a.href = URL.createObjectURL(blob)
  a.download = `AuditPack-${doc.name.replace(/\s+/g, '-')}-${Date.now()}.html`
  a.click()
}
